### ISSUE TITLE
Write integration tests for the new layout algorithm

### ISSUE THREAD

**Issue by gcoutable** [eclipse-sirius/sirius-web#1972] opened 2023-05-15 16:13 UTC
The tests will compare the result of a diagram laid out with the new layout engine exported in SVG

**Comment by sbegaudeau** [comment] 2023-05-15 16:25
Duplicate of https://github.com/eclipse-sirius/sirius-components/issues/1971 :)

**Closed as completed by sbegaudeau** 2023-05-15 16:25 UTC
Labels: difficulty: medium, package: diagrams, type: tests
