### ISSUE TITLE
Widget reference does not work in vs-code extension

### ISSUE THREAD

**Issue by mcharfadi** [eclipse-sirius/sirius-web#2922] opened 2024-01-15 09:39 UTC
The widget reference does not show in a form opened in vs-code extension.

**Comment by gcoutable** [comment] 2024-07-09 12:17
Since https://github.com/eclipse-sirius/sirius-web/issues/3727 describe the issue more precisely, I consider this issue to be the duplicate of https://github.com/eclipse-sirius/sirius-web/issues/3727

**Closed as completed by gcoutable** 2024-07-09 12:17 UTC
Labels: type: bug, resolution: duplicate, difficulty: medium, package: vs-code
