### ISSUE TITLE
Depending on zoom level, the list container borders disappear 

### ISSUE THREAD

**Issue by frouene** [eclipse-sirius/sirius-web#2723] opened 2023-12-01 13:22 UTC
This behavior was only observed on nodes with a list strategy

### Actual behavior

![container_border_disappear](https://github.com/eclipse-sirius/sirius-web/assets/128395825/7fa7df0b-c35c-469c-9d8b-833f5aaa0db3)

**Comment by pcdavid** [comment] 2023-12-01 15:40
It seems to be very dependent on the browser (Firefox seems more subject to the bug than Chrome) and the actual screen (4K _vs_ HD).

In the video below, Firefox (120.0) is on the left, Chromium (119.0) on the right. Both at 100% at the page level. Both start from the same state. This is on Fedora Linux 39, on a 4K screen.

[Capture vidéo du 2023-12-01 16-38-13.webm](https://github.com/eclipse-sirius/sirius-web/assets/10608/8ae909bd-0558-4edf-8d83-c41ea23ff846)

**Comment by pcdavid** [comment] 2023-12-01 15:41
To reproduce, use this studio definition (a modified Papaya Studio): [Papaya Studio.zip](https://github.com/eclipse-sirius/sirius-web/files/13528735/Papaya.Studio.zip)

**Comment by sbegaudeau** [comment] 2023-12-11 00:22
Closing this since there does not seems to be anything we can do

**Closed as completed by sbegaudeau** 2023-12-11 00:22 UTC
Labels: type: bug, difficulty: medium, package: diagrams
